[package]
name = "rust_partdiff"
version = "0.1.0"
authors = ["Michael Blesel <michaelblesel@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

default = []

[dependencies]
ndarray = { git = "https://github.com/felsenhower/ndarray.git", branch = "extend_zip", version = "0.17.1", features = ["rayon"] }
rayon = "1.11.0"
